[my_funds]
funds_names = [
    "华安易富黄金ETC联接C",
    "中银季季享90天滚动持有中短债债券A",
    "中欧电子信息沪港深A 投资增值",
    "天弘越南市场股票(QDII)A",
    "前海开源金银珠宝混合A",
    "华夏标普500ETF联接(QDII)C",
    "招商中证白酒指数C",
    "华宝海外新能源汽车股票(QDII)C",
    "广发纳斯达克100ETF联接(QDII)C"
]
funds_code = [
    "000217",
    "016149",
    "004616",
    "013536",
    "008763",
    "001302",
    "018065",
    "012414",
    "017145",
    "006479"]